[package]
name = "otyugh"
version = "0.1.0"
authors = ["Oblivia Simplex <oblivia@paranoici.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
async-trait = "0.1"
tokio-timer = "0"
indexmap = "1.3"
toml = "0.5"
rand = "0.7"
rand_isaac = "0.2"
unicorn = "0.9"
goblin = "0.2"
lazy_static = "1.4"
rust-ini = "0.15"
distance = "0.4"
serde = "1"
futures = "0.3"
sliding_windows = "3"
log = "0.4"
pretty_env_logger = "0.4"
serde_derive = "1"
