#selection = "Roulette"
selection = "Tournament"
#selection = "Metropolis"
mut_rate = 0.1
crossover_period = 7
crossover_rate = 1.0 # versus clone
max_init_len = 100
min_init_len = 10
pop_size = 512
tournament_size = 8
num_offspring = 2
num_parents = 2
target_fitness = 0
max_length = 100

[hello]
target = "Mares eat oats and does eat oats and little lambs eat ivy."


[machine]
max_steps = 0x1000

[observer]
window_size  = 10_000
report_every = 10_000

[data]
path = "./data/iris.tsv"
#path = "./data/agaricus-lepiota.tsv"

[roper]
use_registers = [ "RAX", "RCX", "RDX" ]
arch = "X86"
mode = "MODE_64"
