##############################
# Documentation forthcoming! #
##############################

job = "Roper"
selection = "Roulette"
#selection = "Tournament" # currently inefficient
#selection = "Metropolis"
mut_rate = 0.1
crossover_period = 3
crossover_rate = 1.0 # versus clone
max_init_len = 100
min_init_len = 10
pop_size = 500
num_offspring = 2
num_parents = 2
target_fitness = 0
max_length = 100

[tournament]
tournament_size = 4

[roulette]
# Should be a float greater than 0.0 and less than 1.0. The lower the value, the more elitist the selection.
weight_decay = 0.7

[hello]
target = "Mares eat oats and does eat oats and little lambs eat ivy."


[machine]
max_steps = 0x1000

[observer]
dump_population = false
dump_soup = false 
data_directory = "~/logs"
window_size  = 10_000
report_every = 10_000

[data]
path = "./data/iris.tsv"
#path = "./data/square.tsv"
#path = "./data/agaricus-lepiota.tsv"

[roper]
arch = "X86"
mode = "MODE_64"
soup_size = 0x1000
binary_path = "/bin/sh"
num_workers = 41
num_emulators = 31
max_emu_steps = 0x1_000
millisecond_timeout = 500
emulator_stack_size = 0x1000
record_basic_blocks = true
output_registers = [ "R10", "RDI", "RSI", "RSP", "RBP", "RIP", "RAX" ]
[roper.register_pattern] 
RCX = "0xbeef"
RDX = "&&0"
RBX = "0xf00d"

