mut_rate = 0.5
init_len = 32
pop_size = 100
tournament_size = 4
num_offspring = 2
# target = "Mares eat oats and does eat oats and little lambs eat ivy."
#target = "Hello, World!"
target = "hello"
target_fitness = 0
max_length = 100

[observer]
window_size = 10000

[data]
path = "./data/i^2+4i-3.tsv"
#path = "./data/sqrt.tsv"
#path = "./data/cubed_plus_squared.tsv"
#path = "./data/square.tsv"
