mut_rate = 0.1
init_len = 32
pop_size = 128
tournament_size = 4
num_offspring = 2
# target = "Mares eat oats and does eat oats and little lambs eat ivy."
#target = "Hello, World!"
target = "hello"
target_fitness = 1
max_length = 100

[observer]
window_size = 10000

[data]
path = "./data/iris.tsv"
#path = "./data/agaricus-lepiota.tsv"
